---
title: "Homework-2"
output: github_document
---

## Library calls
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```


## Problem 1

```{r}
# read csv file
nyc_transit_df = read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
#clean names
nyc_transit_df = janitor::clean_names(nyc_transit_df)
```
```{r}
# retain certain columns in df
nyc_transit_df = nyc_transit_df %>% select(line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, entrance_type, vending, ada) 
```

```{r}
# recode entry variable from character to logical type
nyc_transit_df$entry = ifelse(nyc_transit_df$entry =="YES", TRUE, FALSE)
```
```{r}
#Write a short paragraph about this dataset – explain briefly what variables the dataset contains, describe your data cleaning steps so far, and give the dimension (rows x columns) of the resulting dataset. Are these data tidy?
```

```{r}
#Q: How many distinct stations are there? 
nyc_transit_df %>% 
distinct(line, station_name) %>% 
count()
#A: There are 465 distinct stations in NYC. 
```

```{r}
#Q: How many stations are ADA compliant?
nyc_transit_df %>% 
filter(ada == "TRUE") %>% 
distinct(line, station_name) %>%
count()
#A: 84 stations are ADA compliant. 
```
```{r}
#Q: What proportion of station entrances / exits without vending allow entrance?
nyc_transit_df %>% 
filter(vending == "YES") %>%
count(entry) %>%
mutate(prop = n/sum(n))
#A: 99.94% of station entrances / exits without vending vending allow entrance.
```

```{r}
#Reformat data so that route number and route name are distinct variables.
nyc_transit_df$route8 <- as.character(nyc_transit_df$route8)
nyc_transit_df$route9 <- as.character(nyc_transit_df$route9)
nyc_transit_df$route10 <- as.character(nyc_transit_df$route10)
nyc_transit_df$route11 <- as.character(nyc_transit_df$route11)

nyc_transit_df = 
  pivot_longer(
    nyc_transit_df, 
    route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    names_prefix = "route"
  )
#Q:How many distinct stations serve the A train? 
nyc_transit_df %>%
filter(route_name == "A") %>%
distinct(line, station_name) %>%
count()
#A: 60 distinct stations serve the A train. 
```
```{r}
#Q: Of the stations that serve the A train, how many are ADA compliant?
nyc_transit_df %>%
filter(route_name == "A") %>%
filter(ada == "TRUE") %>%
distinct(line, station_name) %>%
count()
#A: Of the 60 stations that serve the A train, 17 are ADA compliant. 
```

## Problem 2

```{r}
# Read data for Mr. Trash Wheel
mr_trash_df = read_excel("trash_wheel_data.xlsx", sheet = 1, range = cell_cols("A:N"))
# clean names
mr_trash_df = janitor::clean_names(mr_trash_df)
#remove any rows without dumpster-specific data
mr_trash_df = mr_trash_df %>%
  filter(!is.na(dumpster))
#round number of sports balls to the nearest integer and converts the result to an integer variable
mr_trash_df$sports_balls <- round(mr_trash_df$sports_balls)
mr_trash_df$sports_balls <- as.integer(mr_trash_df$sports_balls)
#add new variable to indicate sheet number
mr_trash_df$sheet <- "Mr. Trash Wheel"
```

```{r}
# Read data for Professor Trash Wheel
prof_trash_df = read_excel("trash_wheel_data.xlsx", sheet = 2, range = cell_cols("A:M"))
# clean names
prof_trash_df = janitor::clean_names(prof_trash_df)
#remove any rows without dumpster-specific data
prof_trash_df = prof_trash_df %>%
  filter(!is.na(dumpster))
#round number of sports balls to the nearest integer and converts the result to an integer variable

#^ DOUBT!!!

#add new variable to indicate sheet number
prof_trash_df$sheet <- "Professor Trash Wheel"

#combine datasets
prof_trash_df$year <- as.character(prof_trash_df$year)
joint_trash_df <- full_join(mr_trash_df, prof_trash_df)

```
```{r}
#Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in the resulting dataset, and give examples of key variables. 

#DO THIS!!!
```

```{r}
#Q: What was the total weight of trash collected by Professor Trash Wheel?
joint_trash_df %>% 
  filter(sheet == "Professor Trash Wheel") %>%
  summarise(total_weight = sum(weight_tons))
#A: The total weight of trash collected by Professor Trash is 190.12 tons. 
```
```{r}
#Q: What was the total number of sports balls collected by Mr. Trash Wheel in 2020?
joint_trash_df %>% 
  filter(sheet == "Mr. Trash Wheel" & year == 2020) %>%
  summarise(total_balls = sum(sports_balls))
#A: Mr. Trash Wheel collected a total of 856 sports balls in 2020. 
```

## Problem 3
```{r}
# read and clean the data in pols-month.csv
pols_month_df = read_csv("problem3_data/pols-month.csv")
#clean names
pols_month_df = janitor::clean_names(pols_month_df)
# Use separate() to break up the variable mon into integer variables year, month, and day AND replace month number with month name
pols_month_df = pols_month_df %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  arrange(year, month) %>%
  mutate(month = recode(month, "01" = "January", "02" = "February", 
                        "03" = "March", "04" = "April", "05" = "May", 
                        "06" = "June", "07" = "July", "08" = "August",
                        "09" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))

#create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable
pols_month_df$president = paste(pols_month_df$prez_dem, ",", pols_month_df$prez_gop)

pols_month_df = subset(pols_month_df, select = -c(prez_dem, prez_gop, day))
#arrange df according to year and month
```

```{r}
# read and clean the data in snp.csv
snp_df = read_csv("problem3_data/snp.csv")
#clean names
snp_df = janitor::clean_names(snp_df)
# Use separate() to break up the variable mon into integer variables year, month, and day
snp_df = snp_df %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>%
  arrange(year, month) %>%
  select(-day) 
##DOUBT^^(How to arrange according to year)

#organize so that year and month are the leading columns
snp_df <- snp_df[, c(2,1,3)]
#edit year column
snp_df$year[1:187] = paste0("20", snp_df$year[1:187])
snp_df$year[188:787] = paste0("19", snp_df$year[188:787])
#make month numeric type
snp_df$month <- as.numeric(snp_df$month)
#arrange snp_df again according to year and replace month number with month name
snp_df = snp_df %>%
  arrange(year, month) %>%
  mutate(month = recode(month, "1" = "January", "2" = "February", 
                        "3" = "March", "4" = "April", "5" = "May", 
                        "6" = "June", "7" = "July", "8" = "August",
                        "9" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))
```

```{r}
# read and clean the data in unemployment.csv
unemployment_df = read_csv("problem3_data/unemployment.csv")
#clean names
unemployment_df = janitor::clean_names(unemployment_df)
#pivot_longer month
unemployment_df = 
  pivot_longer(
    unemployment_df, 
    jan:dec,
    names_to = "month",
    values_to = "unemployment_value"
  )
unemployment_df = unemployment_df %>%
  mutate(month = recode(month, "jan" = "January", "feb" = "February", 
                        "mar" = "March", "apr" = "April", "may" = "May", 
                        "jun" = "June", "jul" = "July", "aug" = "August",
                        "sep" = "September", "oct" = "October", 
                        "nov" = "November", "dec" = "December"))
```
```{r}
pols_snp_joint = left_join(pols_month_df, snp_df)
unemployment_df$year = as.character(unemployment_df$year)
pols_snp_unemp_joint = left_join(pols_snp_joint, unemployment_df)
```

